export const coins = [
  {code: 'ANT', name: 'Aragon'},
  {code: 'REP', name: 'Augur'},
  {code: 'BAT', name: 'Basic Attention Token'},
  {code: 'BTC', name: 'Bitcoin'},
  {code: 'BCH', name: 'Bitcoin Cash'},
  {code: 'BCY', name: 'BitCrystals'},
  {code: 'CLAM', name: 'CLAMS'},
  {code: 'DCR', name: 'Decred'},
  {code: 'DASH', name: 'DigitalCash'},
  {code: 'DOGE', name: 'Dogecoin'},
  {code: 'EDG', name: 'Edgeless'},
  {code: 'EOS', name: 'EOS'},
  {code: 'ETH', name: 'Ethereum'},
  {code: 'ETC', name: 'Ethereum Classic'},
  {code: 'FLO', name: 'FlorinCoin'},
  {code: 'FLDC', name: 'Folding Coin'},
  {code: 'FUN', name: 'FunFair'},
  {code: 'GAME', name: 'Gamecredits'},
  {code: 'GNO', name: 'Gnosis'},
  {code: 'HT', name: 'Huobi Token'},
  {code: 'RLC', name: 'iExec'},
  {code: 'LTC', name: 'Litecoin'},
  {code: 'MLN', name: 'Melon'},
  {code: 'XMR', name: 'Monero'},
  {code: 'NEO', name: 'NEO'},
  {code: 'NXC', name: 'Nexium'},
  {code: 'OMNI', name: 'Omni'},
  {code: 'PINK', name: 'PinkCoin'},
  {code: 'POT', name: 'PotCoin'},
  {code: 'XRP', name: 'Ripple'},
  {code: 'STEEM', name: 'Steem'},
  {code: 'SBD', name: 'Steem Backed Dollars'},
  {code: 'AMP', name: 'Synereo'},
  {code: 'TRX', name: 'Tronix'},
  {code: 'XVC', name: 'Vcash'},
  {code: 'VIA', name: 'ViaCoin'}
]
